import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { graphqlClient } from "@clients/graphqlClient";
import Link from "next/link";

import { GetJobsDocument, GetJobsQuery } from "src/graphql/generated/graphql";

export const getStaticProps: GetStaticProps = async () => {
  try {
    const data: GetJobsQuery = await graphqlClient(GetJobsDocument);

    return {
      props: { data },
      revalidate: 21600,
    };
  } catch (error: any) {
    throw new Error(error);
  }
};

const Home: NextPage = ({ data }: any) => {
  const jobs = data.jobs;
  return (
    <div className="text-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {jobs.map((job: any) => (
        <div key={job.id} className="text-center px-6 pt-4 pb-2">
          <a className="text-center inline-block bg-gray-200 rounded-xl px-12 py-5 text-sm font-semibold text-gray-700 mr-2 mb-2 hover:bg-white cut">
            <h2>{job.title}</h2>
            <p>{job.salary}</p>
          </a>
        </div>
      ))}
      <Link href="/job">
        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded text-center">Add job</button>
      </Link>
    </div>
  );
};

export default Home;
